### ISSUE TITLE
Boleto não aparece. O que pode ser?

### ISSUE THREAD

**Issue by kleytonbarcelos** [natanfelles/codeigniter-boleto#1]
Boleto não aparece. O que pode ser? Coloquei numa instalação (limpa) do Codeiginiter 3.1, e não rodou. O que pode está acontecendo?

VEJA: https://ctrlv.cz/dJ1M

**Comment by kleytonbarcelos** [comment]
Já consegui resolver. É porque no Codeigniter 3.1, não se usa o nome: Boleto_controller para o controler. E o erro aconteceu justamente pois eu havia renomeado esse CONTROLLER para  (Boleto.php) e quando executava o nome do Controller estava igual a da librari (Boleto) e também confundia com as variáveis do config.

Resumindo: quando baixarem esse código e forem usar no CODEIGNITER 3.1 (>) não se esqueçan de renomear o Boleto_controller para outro nome exe.: Teste.php e o código vai rodar direitinho.

**Comment by natanfelles** [comment]
O arquivo `application/controllers/Boleto_controller.php` é apenas um exemplo de uso e pode ser acessado pelo navegador em `SITE_URL/boleto_controller`. Não há necessidade de ser renomeado.
