### ISSUE TITLE
Imprimir em PDF

### ISSUE THREAD

**Issue by wagnerfillio** [natanfelles/codeigniter-boleto#3]
Olá,

Tentei usar a biblioteca MPDF e DOMPDF para converter os boletos em PDF, mas não consigo, por dar erro no cabeçalho.

Podes indicar alguma solução ?

**Comment by natanfelles** [comment]
Olá, @wagnerfillio !

Nessa biblioteca foi utilizado `include` para obter o layout dos boletos:

https://github.com/natanfelles/codeigniter-boleto/blob/ef590ade850e82b30d7bb4b237902958dda0dfe7/application/libraries/Boleto.php#L113

Seria ótimo receber uma PR para otimizar isso. No caso, poderia ser utilizado apenas um método com parâmetros para os dados e o nome do layout boleto.

Então o layout poderia retornar numa string, como:

```php
ob_start();
include 'layout-x.php';
return ob_get_clean();
```

Isso resolveria o problema com cabeçalhos.

**Comment by natanfelles** [comment]
A adição de setters e getters também seria ótimo. :)

**Comment by wagnerfillio** [comment]
Olá @natanfelles,

Obrigado pelo retorno!

Da forma que colocou no exemplo, até funcionou, mas parece que o CSS não funciona tão bem, e há demasiado tempo na geração do PDF (acredito que muito em função da biblioteca mPDF).

Agora pode me dá uma luz, de como seria a sua ideia de otimização ?
