### ISSUE TITLE
Retornar dados do boleto para inserir no banco de dados

### ISSUE THREAD

**Issue by wagnerfillio** [natanfelles/codeigniter-boleto#4]
Olá,

Sabe como poderia recuperar os dados do boleto `dadosboleto` para incluir no banco de dados ?

Exemplo: return $dadosboleto;
Daí eu pegaria o retorno no controller ou no model e salvaria no banco de dados.

**Comment by natanfelles** [comment]
Olá, Wagner!

Para gerar os boletos é necessário que os dados já sejam definidos pelo desenvolvedor.

Basicamente, todos os métodos chamam o `setup`.

https://github.com/natanfelles/codeigniter-boleto/blob/ef590ade850e82b30d7bb4b237902958dda0dfe7/application/libraries/Boleto.php#L215-L221

**Comment by wagnerfillio** [comment]
Entendo, mas neste caso , consigo recuperar somente os dados que incluímos no boleto:

Como sacado, cedente, endereço..

Estava querendo o retorno da `linha digitável` e do `código de barras` para fazer um insert no MySQL
